apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        # Make sure this is v29 to include your SmtpEmailSender fix!
        image: albanianquoraregistry123.azurecr.io/albanianquora-backend:v33
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: ConnectionStrings__DefaultConnection
        - name: Email__SmtpHost
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: Email__SmtpHost
        - name: Email__SmtpPort
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: Email__SmtpPort
        - name: Email__Username
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: Email__Username
        - name: Email__Password
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: Email__Password
        - name: Email__From
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: Email__From