apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        # CORRECTED IMAGE URL
        image: albanianquoraregistry123.azurecr.io/albanian-quora-be:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: ConnectionStrings__DefaultConnection

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: backend-deployment
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: backend
#   template:
#     metadata:
#       labels:
#         app: backend
#     spec:
#       containers:
#       - name: backend
#         image: albanianquoraacr.azurecr.io/albanianquora-backend:v6
#         ports:
#         - containerPort: 8080
#         env:
#         - name: ConnectionStrings__DefaultConnection
#           valueFrom:
#             secretKeyRef:
#               name: backend-secrets
#               key: ConnectionStrings__DefaultConnection