apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: albanianquoraregistry123.azurecr.io/albanianquora-frontend:v46
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: VITE_API_URL
          value: "http://20.103.169.185/api"